# Generated by Django 4.1.7 on 2023-03-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(default='abcd@gmail.com', max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000000)),
                ('description', models.TextField(default='Null.')),
            ],
        ),
    ]
